### ISSUE TITLE
Is it possible to connect when it reports 'All sockets closed.'

### ISSUE THREAD

**Issue by NewReStarter** [enobufs/stun#14]
When it completes, it suggests the following info.

Complete(0): Open NB=I EF=I (Open to internet) mapped=144.214.112.87:59390 rtt=0
All sockets closed.

Is it possible to keep the socket open?

**Comment by andyoknen** [comment]
Just comment out the socket close call https://github.com/enobufs/stun/blob/5e417950733bf7528d4cfa645c2d08048eed585a/bin/client.js#L34
