### ISSUE TITLE
Suggestion: self configuration using available interfaces

### ISSUE THREAD

**Issue by pj-gomez** [enobufs/stun#7]
I've thinking that it would be useful to have a zero configuration fallback (in the case the .ini file is missing or even if some parameter in it is set to 'automatic') so the system retrieves the list of available network interfaces and uses that information to self-configure.
If you like the idea, I can work on that and pull it when it's ready.

**Comment by enobufs** [comment]
I really don't see much benefit from zero configuration where that could potentially cause the server silently bootup with out config. Also, current spec requires two IPs (based on RFC 3489), it is hard to setup a meaningful secondary IP. If we remove the requirement for the secondary IP (meaning, going to RFC 5389, then the IP address could be ANY (0.0.0.0), which would probably be the best default IP address for the server. So, let's not worry about it now.

**Comment by pj-gomez** [comment]
Undestood, tell me if there is anything in particular you want me to work on.
